# Generated by Django 4.2.5 on 2023-10-12 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_participant_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="participant",
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
