# Generated by Django 4.2.5 on 2023-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
