# Generated by Django 4.2.5 on 2023-10-12 18:59

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_like_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="like",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="comment",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="like",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
