# Generated by Django 4.2.5 on 2023-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_comment_options_alter_like_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("participant_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
