# Generated by Django 4.2.5 on 2023-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_comment_options_alter_like_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="article",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="publisher",
            name="is_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
