# Generated by Django 4.2.5 on 2023-10-12 19:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_participant_session"),
        ("articles", "0005_remove_like_article_remove_like_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("content", models.TextField()),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
