# Generated by Django 4.2.5 on 2023-10-23 17:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_participant_session"),
        ("articles", "0005_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleTimeSpent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "unique_together": {("session", "article")},
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("L", "Like"),
                            ("LV", "Love"),
                            ("C", "Care"),
                            ("W", "WOW"),
                            ("H", "Haha"),
                            ("S", "Sad"),
                            ("A", "Angry"),
                        ],
                        max_length=3,
                    ),
                ),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                (
                    "participant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.participant"),
                ),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "unique_together": {("participant", "article")},
            },
        ),
        migrations.CreateModel(
            name="ReadEntireArticleClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                (
                    "participant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.participant"),
                ),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")),
                (
                    "participant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.participant"),
                ),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.session")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="like",
            name="article",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="session",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="users.session"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="is_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
