# Generated by Django 4.2.5 on 2023-10-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_articlesent_articletimespent_reaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
