# Generated by Django 4.2.5 on 2024-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_category_article_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareclick",
            name="shared_on",
            field=models.CharField(
                choices=[
                    ("FB", "FACEBOOK"),
                    ("X", "TWITTER"),
                    ("C", "COPY"),
                    ("I", "INSTAGRAM"),
                    ("L", "LINKEDIN"),
                    ("R", "REDDIT"),
                ],
                default="C",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
