# Generated by Django 4.2.5 on 2024-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_shareclick_shared_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="publishers"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
