# Generated by Django 4.2.5 on 2024-05-06 19:46

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_publisher_image_publisher_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", models.TextField()),
                ("primary_button", models.CharField(max_length=255)),
                ("secondary_button", models.CharField(max_length=255)),
                ("minutes", models.PositiveIntegerField()),
                ("survey_link", models.URLField(max_length=1000)),
                ("follow_up_content", models.TextField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
